# Cifras reales 2T 2026 de las 10 fichas que antes tenían datos ilustrativos.
# Fuente: guiones de cada video en /mnt/project-files/<empresa>/guion-2T26.md (estados financieros, análisis razonado,
# comunicados; AFP: Superintendencia de Pensiones). (c) = cifra calculada por nosotros. Lo usa reales.py.
R = [
 dict(id="andina-a", t="ANDINA-A", n="Embotelladora Andina (Serie A)", s="Bebidas", px="$3.903", chg=19,
  pe=12.7, fpe=11.8, pbv=None, ev=7.5, dy=5.2, roe=23.4, epsg=0.0, vid="01NKY2CQ03E", q="Andina",
  lede="Embotelladora de Coca-Cola en Chile, Argentina, Brasil y Paraguay. La serie A tiene mayores derechos políticos y la serie B mayores derechos económicos, por eso cotizan a precios distintos. Reporta en pesos.",
  vtitle="Embotelladora Andina: EBITDA +17%, pero la utilidad no crece (2T 2026)",
  cap="Cifras en CLP miles de millones salvo BPA · 2T 2026 vs. 2T 2025",
  rows=[("Ventas netas", 738.2, 820.1, 1), ("Ganancia bruta", 279.8, 319.2, 1), ("EBITDA ajustado", 119.3, 139.6, 1),
        ("Resultado operacional", 79.9, 93.2, 1), ("Utilidad atribuible", 37.2, 37.3, 1), ("BPA (CLP por acción)", 39, 39, 0)],
  derived=("Margen EBITDA", "16,2%", "17,0%"),
  kpi="Deuda financiera neta US$802 MM: <b>1,1x</b> EBITDA. Ventas 1,4% sobre el consenso, pero BPA de $39 vs. $55,80 esperado (−30%) por la inflación en UF y mayores impuestos.",
  tiles=[("P/E", "12,7x"), ("Forward P/E", "11,8x"), ("EV/EBITDA", "7,5x"), ("FCF yield", "7,4%"), ("Dividend Yield", "5,2%"), ("ROE", "23,4%")],
  small="P/E y forward P/E con el precio de la serie A (de la empresa completa: 14,4x y 13,8x) · P/E histórico 11,3x–15,7x (2021–2025) · ROE <b>23,4%</b>.",
  mirar=["Brasil (+21% en ventas) y Paraguay (+31%), hoy los motores del crecimiento.", "Argentina: volumen −6,6% y riesgo cambiario.", "Inflación en UF, que encarece la deuda y se comió la utilidad del trimestre.", "Múltiplos sobre su historia: EV/EBITDA de 7,5x vs. 5–6x."],
  var={"Ventas netas": 11.1, "Ganancia bruta": 14.1, "EBITDA ajustado": 17.0, "Resultado operacional": 16.7, "Utilidad atribuible": 0.1, "BPA (CLP por acción)": 0.0}),
 dict(id="besalco", t="BESALCO", n="Besalco S.A.", s="Construcción e ingeniería", px="$1.310", chg=37,
  pe=11.9, fpe=14.3, pbv=None, ev=6.5, dy=None, roe=None, epsg=-9.4, vid="qHGlhMQsm-U", q="Besalco",
  lede="Grupo de ingeniería y construcción con obras civiles, montaje industrial, arriendo de maquinaria, desarrollo inmobiliario y concesiones. Su backlog (cartera de obras por ejecutar) es clave para anticipar ingresos. Reporta en pesos.",
  vtitle="Besalco: ingresos −6,6% y utilidad −9%, con backlog récord (2T 2026)",
  cap="Cifras en CLP miles de millones salvo BPA · 2T 2026 vs. 2T 2025",
  rows=[("Ingresos", 242.9, 227.0, 1), ("Ganancia bruta", 35.3, 28.3, 1), ("EBITDA", 42.1, 38.7, 1),
        ("Utilidad controladora", 10.4, 9.5, 1), ("BPA (CLP por acción)", 18.1, 16.4, 1)],
  derived=("Margen EBITDA", "17,3%", "17,0%"),
  kpi="Deuda financiera neta / EBITDA: <b>2,44x</b> (1,99x un año antes). Backlog de UF 44,2 MM (+12,7%). En el semestre la utilidad sube 10,9%. No hay consenso público: se compara con el 2T 2025.",
  tiles=[("P/E", "11,9x"), ("Forward P/E", "14,3x"), ("EV/EBITDA", "6,5x"), ("FCF yield 2025", "2,4%"), ("Deuda neta / EBITDA", "2,44x"), ("Backlog", "UF 44,2 MM")],
  small="P/E histórico 4,8x–11,4x (2021–2025) · Flujo de caja libre del semestre negativo (−$20,4 mil MM) por compras de maquinaria · Forward P/E con la estimación de Bci.",
  mirar=["Backlog récord de UF 44 MM, que anticipa ingresos.", "Margen bruto que bajó a 12,5% (14,5% un año antes).", "Deuda neta que subió a 2,44x EBITDA.", "Flujo de caja libre negativo en el semestre."],
  var={"Ingresos": -6.6, "EBITDA": -8.2, "Utilidad controladora": -9.0}),
 dict(id="chile", t="CHILE", n="Banco de Chile", s="Banca", px="ADS US$42,07", chg=29,
  pe=15.9, fpe=14.7, pbv=3.3, ev=None, dy=4.7, roe=27.9, epsg=28.1, vid="2oA-4YLJhQI", q="Banco de Chile",
  lede="Uno de los dos bancos privados más grandes del país, controlado por Quiñenco (grupo Luksic) junto a Citigroup. Destaca por su alta rentabilidad sobre el patrimonio, baja morosidad y una política de dividendos generosa. Cotiza en Santiago y como ADS en Nueva York.",
  vtitle="Banco de Chile: utilidad récord, 24% sobre el consenso (2T 2026)",
  cap="Cifras en CLP miles de millones salvo BPA · 2T 2026 vs. 2T 2025",
  rows=[("Ingresos operacionales", 763, 922, 0), ("Utilidad neta", 304.9, 390.6, 1), ("BPA (CLP por acción)", 3.02, 3.87, 2)],
  derived=None,
  kpi="BPA de US$0,84 por ADS vs. US$0,68 esperado por el consenso (+24%); ingresos 2,7% sobre lo estimado. Eficiencia <b>31,3%</b>, ROAE 27,9% (el segundo del sistema), CET1 13,9%, costo de riesgo 1,65% y morosidad 1,6%.",
  tiles=[("P/E", "15,9x"), ("Forward P/E", "14,7x"), ("P/BV", "3,3x"), ("ROAE", "27,9%"), ("Dividend Yield", "4,7%"), ("Eficiencia", "31,3%")],
  small="ROE <b>27,9%</b> · Bajó su guía 2026: colocaciones ~6% (antes ~7%) y costo de riesgo 1,2–1,3% · EV/EBITDA y FCF yield no aplican a bancos · P/E histórico 8,4x (2023) a 14,7x (2025).",
  mirar=["Inflación: el margen de interés (NIM) bajaría hacia ~4,6% si la UF sube menos.", "Costo de riesgo al alza (guía 1,2–1,3%).", "Crecimiento de colocaciones débil (+2,3%).", "Valoración exigente: P/BV de 3,3x."],
  var={"Ingresos operacionales": 20.9, "Utilidad neta": 28.1, "BPA (CLP por acción)": 28.1}),
 dict(id="cmpc", t="CMPC", n="Empresas CMPC", s="Forestal y celulosa", px="$990", chg=-32,
  pe=24.0, fpe=13.0, pbv=0.27, ev=7.2, dy=None, roe=None, epsg=-89.0, vid="lBozESCSZbQ", q="CMPC",
  lede="Empresa forestal del grupo Matte con tres negocios: celulosa, papeles y cartones (Biopackaging) y productos de consumo como papel tissue (Softys). Tiene operaciones en Chile, Brasil y otros países de Latinoamérica. Su utilidad depende sobre todo del precio internacional de la celulosa. Reporta en dólares.",
  vtitle="CMPC: utilidad −89% y deuda de 4,2x EBITDA (2T 2026)",
  cap="Cifras en US$ millones salvo EPS · 2T 2026 vs. 2T 2025",
  rows=[("Ingresos", 1907, 1916, 0), ("Ganancia bruta", 656, 618, 0), ("EBITDA ajustado", 332, 270, 0),
        ("Resultado operacional", 158, 89, 0), ("Utilidad controladores", 81, 9, 0), ("EPS (US$ por acción)", 0.0324, 0.0036, 4)],
  derived=("Margen EBITDA", "17,4%", "14,1%"),
  kpi="Deuda neta / EBITDA: <b>4,17x</b> (3,65x un año antes; meta 2,5–3,5x). EPS de ~US$0,0036 vs. US$0,0065 esperado por el consenso. Flujo de caja libre del trimestre US$174 MM (c), con capex −48%.",
  tiles=[("P/E", "~24x"), ("Forward P/E", "~13x"), ("EV/EBITDA", "7,2x"), ("FCF yield 2026e", "4,2%"), ("P/BV", "0,27x"), ("Deuda neta / EBITDA", "4,17x")],
  small="Vendió su negocio de corrugados a Smurfit Westrock por US$420 MM (7,6x EBITDA), sujeto a la FNE · EV/EBITDA histórico 3,9x–8,4x (2021–2025) · P/BV <b>0,27x</b>.",
  mirar=["Precio de la celulosa (BHKP US$600/t, +7% en el trimestre) y demanda de China.", "Deuda de 4,17x EBITDA y costo financiero de US$95 MM por trimestre.", "Softys: EBITDA +24%, el negocio que mejor anduvo.", "Proyecto Natureza en Brasil (US$4.600 MM), aún sin decisión."],
  var={"Ingresos": 0.5, "EBITDA ajustado": -18.7, "Utilidad controladores": -88.9, "EPS (US$ por acción)": -88.9}),
 dict(id="copec", t="COPEC", n="Empresas Copec", s="Holding: forestal y combustibles", px="$6.600", chg=-9,
  pe=7.7, fpe=12.0, pbv=None, ev=5.8, dy=2.8, roe=None, epsg=88.9, vid="Y2Az8KiZOek", q="Copec",
  lede="Holding del grupo Angelini con dos grandes negocios: Arauco (celulosa, madera y paneles) y Copec combustibles (estaciones de servicio en Chile y Terpel en Colombia y otros países). Además participa en minería (Mina Justa), gas licuado (Abastible) y pesca. Reporta en dólares.",
  vtitle="Empresas Copec: utilidad +93%, muy sobre el consenso (2T 2026)",
  cap="Cifras en US$ millones salvo EPS · 2T 2026 vs. 2T 2025",
  rows=[("Ingresos", 7181, 9246, 0), ("EBITDA", 713, 1029, 0), ("EBITDA ajustado", 797, 1037, 0),
        ("Resultado operacional", 376, 556, 0), ("Utilidad atribuible", 228, 440, 0), ("EPS (US$ por acción)", 0.18, 0.34, 2)],
  derived=("Margen EBITDA", "9,9%", "11,1%"),
  kpi="Deuda neta / EBITDA ajustado: <b>3,13x</b> (2,54x un año antes). EPS de US$0,34 vs. US$0,196 esperado por el consenso (+73%). Sin la venta de bosques ni el efecto de inventarios, la utilidad habría sido ~US$313 MM (+37%) (c).",
  tiles=[("P/E", "7,7x"), ("Forward P/E", "~12x"), ("EV/EBITDA", "5,8x"), ("FCF yield 12m", "−17%"), ("Dividend Yield", "~2,8%"), ("Precio objetivo", "$7.461")],
  small="EV/EBITDA sobre EBITDA ajustado (6,2x sobre el reportado) · Capex 2026 de US$3.000–3.400 MM · Sucuriú (Brasil) con 74,5% de avance, partida en el 4T 2027.",
  mirar=["Calidad de la utilidad: venta de bosques e inventarios de combustibles.", "Precio de la celulosa y demanda de China.", "Deuda de 3,1x EBITDA y flujo de caja libre negativo por el capex.", "Avance de Sucuriú y del cobre (Mina Justa, EBITDA +27%)."],
  var={"Ingresos": 28.8, "EBITDA": 44.3, "EBITDA ajustado": 30.1, "Resultado operacional": 47.9, "Utilidad atribuible": 92.6}),
 dict(id="iam", t="IAM", n="Inversiones Aguas Metropolitanas", s="Holding sanitario", px="$927,74", chg=2,
  pe=13.5, fpe=12.1, pbv=None, ev=8.8, dy=5.4, roe=None, epsg=-41.0, vid="RD8A0USvFMI", q="IAM",
  lede="Holding que controla el 50,1% de Aguas Andinas, la sanitaria que abastece a Santiago. IAM es a su vez controlada por Veolia. Su valor depende casi por completo de los dividendos de Aguas Andinas, y suele cotizar con descuento frente al valor de esa participación. Reporta en pesos.",
  vtitle="IAM: EBITDA +7%, pero la utilidad cae 41% por la inflación (2T 2026)",
  cap="Cifras en CLP miles de millones salvo BPA · consolidado · 2T 2026 vs. 2T 2025",
  rows=[("Ingresos", 165.0, 175.9, 1), ("EBITDA", 74.6, 80.1, 1), ("Resultado de explotación", 53.0, 57.3, 1),
        ("Utilidad atribuible", 11.7, 6.9, 1), ("BPA (CLP por acción)", 11.69, 6.90, 2)],
  derived=("Margen EBITDA", "45,2%", "45,6%"),
  kpi="Deuda neta / EBITDA: <b>3,54x</b> (3,62x en dic-2025), 97,9% a tasa fija. El resultado financiero empeoró 91% por la UF. En el semestre la utilidad sube 2,2%. No hay consenso trimestral: se compara contra el 2T 2025.",
  tiles=[("P/E", "13,5x"), ("Forward P/E", "12,1x"), ("EV/EBITDA", "8,8x"), ("FCF yield", "~7,4%"), ("Dividend Yield", "5,4%"), ("Descuento vs. Aguas Andinas", "~7%")],
  small="P/E histórico 12,4x (2024) y 15,0x (2025) · Aguas Andinas transa a 13,2x forward y 8,6x EV/EBITDA · Tarifas del VIII proceso tarifario 2025–2030 al alza.",
  mirar=["Inflación: la deuda en UF pesa en el resultado financiero.", "Capex +27% en el semestre, que reduce el flujo libre.", "Hidrología: el embalse El Yeso al 65%.", "Cambios tributarios y regulatorios (proyecto de rebaja del impuesto corporativo)."],
  var={"Ingresos": 6.6, "EBITDA": 7.4, "Resultado de explotación": 8.0, "Utilidad atribuible": -41.0, "BPA (CLP por acción)": -41.0}),
 dict(id="habitat", t="HABITAT", n="AFP Habitat", s="AFP", px="$1.426", chg=12,
  pe=8.1, fpe=None, pbv=None, ev=8.5, dy=7.0, roe=None, epsg=19.6, vid="M7fElTXELSA", q="Habitat",
  lede="Administradora de fondos de pensiones controlada en partes iguales por la Cámara Chilena de la Construcción y Prudential Financial. Es la AFP con mayor patrimonio administrado. Sus ingresos vienen de la comisión sobre el sueldo imponible de sus cotizantes; el encaje (la inversión obligatoria en sus propios fondos) hace que la utilidad varíe con la rentabilidad de los mercados.",
  vtitle="AFP Habitat: utilidad +19,6% gracias al encaje (2T 2026)",
  cap="Cifras en CLP miles de millones salvo BPA · 2T 2026 vs. 2T 2025",
  rows=[("Ingresos por comisiones", 64.68, 67.41, 2), ("Rentabilidad del encaje", 24.94, 34.25, 2), ("Gastos operativos", 25.71, 27.18, 2),
        ("Ganancia antes de impuestos", 63.50, 74.83, 2), ("Utilidad neta", 46.83, 56.01, 2), ("Utilidad sin encaje (c)", 28.1, 29.6, 1), ("BPA (CLP por acción)", 46.8, 56.0, 1)],
  derived=("Margen operacional sin encaje", "60,2%", "59,7%"),
  kpi="Deuda neta mínima (~$20,9 mil MM, ≈0,1x EBITDA). Comisión de 1,27% sin cambios. En el semestre la utilidad sube 9,8%. No hay consenso de analistas: se compara contra el 2T 2025.",
  tiles=[("P/E", "8,1x"), ("EV/EBITDA sin encaje", "8,5x"), ("FCF yield", "3,4%"), ("Dividend Yield", "7,0%"), ("Comisión", "1,27%"), ("Afiliados", "1,70 MM")],
  small="P/E histórico 4,5x–9,0x (2022–2025) · El encaje explica el 46% de la ganancia antes de impuestos · Dividendos de 12 meses: $100 por acción.",
  mirar=["Rentabilidad del encaje, que mueve la utilidad (en el 1T 2026 fue solo $1,4 mil MM).", "Reforma de pensiones: licitación del 10% de afiliados desde 2027 y menor encaje.", "Comisión estable de 1,27% e ingresos +4,2%.", "Dividendos (7%) mayores que el flujo de caja libre."],
  var={"Ingresos por comisiones": 4.2, "Rentabilidad del encaje": 37.3, "Gastos operativos": 5.7, "Ganancia antes de impuestos": 17.8, "Utilidad neta": 19.6, "Utilidad sin encaje (c)": 5.2}),
 dict(id="provida", t="PROVIDA", n="AFP Provida", s="AFP", px="$5.150", chg=29,
  pe=10.6, fpe=None, pbv=None, ev=10.9, dy=7.2, roe=None, epsg=41.0, vid="q_I5RpNMgyM", q="Provida",
  lede="La AFP con más afiliados del sistema (2,49 millones), controlada por la estadounidense MetLife. Su gran base de clientes le da escala y un flujo estable de comisiones; cobra la comisión más alta del sistema (1,45%). La acción casi no transa porque MetLife tiene más del 90%.",
  vtitle="AFP Provida: utilidad +41%, pero el negocio no creció (2T 2026)",
  cap="Cifras en CLP miles de millones salvo BPA · 2T 2026 vs. 2T 2025",
  rows=[("Ingresos ordinarios", 67.98, 63.59, 2), ("Ingresos por comisiones", 64.07, 62.39, 2), ("Rentabilidad del encaje", 17.95, 24.39, 2),
        ("Otros ingresos no operacionales", 0.13, 17.35, 2), ("Ganancia antes de impuestos", 54.31, 76.13, 2), ("Utilidad neta", 40.78, 57.49, 2), ("BPA (CLP por acción)", 124.3, 175.3, 1)],
  derived=("Margen operacional sin encaje", "50,3%", "48,8%"),
  kpi="Sin deuda financiera: caja neta ~$114,9 mil MM. La utilidad incluye la venta de AFP Génesis (Ecuador); sin ella habría sido ~$40,5 mil MM (−0,7%) (c). Fue la AFP con más salidas netas de afiliados entre enero y julio de 2026.",
  tiles=[("P/E", "10,6x"), ("P/E sin Génesis", "11,9x"), ("EV/EBITDA sin encaje", "10,9x"), ("FCF yield 2025", "9,0%"), ("Dividend Yield", "7,2%"), ("Comisión", "1,45%")],
  small="Liquidez casi nula (~700 acciones al día): precio y múltiplos referenciales · P/E histórico 7,6x (2024) y 12,2x (2025) · Flujo operacional del 1S 2026 negativo por impuestos y pagos a aseguradoras.",
  mirar=["Fuga de afiliados: comisiones −2,6% mientras sus pares crecen.", "Utilidad apoyada en la venta de Génesis y en el encaje.", "Gasto en personal −15,9%: ¿ahorro que se mantiene?", "Reforma de pensiones (licitación 2027) con la comisión más alta del sistema."],
  var={"Ingresos ordinarios": -6.5, "Ingresos por comisiones": -2.6, "Rentabilidad del encaje": 35.9, "Otros ingresos no operacionales": None, "Ganancia antes de impuestos": 40.2, "Utilidad neta": 41.0}),
 dict(id="afpcapital", t="AFPCAPITAL", n="AFP Capital", s="AFP (no cotiza en bolsa)", px="No cotiza", chg=None,
  pxnote="Valor de referencia por múltiplos de pares: ~$1.225 mil MM",
  pe=None, fpe=None, pbv=None, ev=None, dy=None, roe=23.7, epsg=None, vid="QPJNFBztng8", q="Capital",
  lede="Administradora de fondos de pensiones controlada por SURA Asset Management (grupo colombiano Sura) desde 2011. No cotiza en bolsa, por eso su valor se estima con los múltiplos de las AFP que sí cotizan. Sus ingresos vienen de la comisión sobre el sueldo imponible de sus cotizantes; el encaje hace que la utilidad varíe con los mercados.",
  vtitle="AFP Capital: utilidad +13%, solo gracias al encaje (2T 2026)",
  cap="Cifras en CLP miles de millones · 2T 2026 vs. 2T 2025",
  rows=[("Ingresos por comisiones", 53.24, 55.63, 2), ("Rentabilidad del encaje", 17.38, 23.71, 2), ("Gastos operativos", 26.26, 29.57, 2),
        ("Ganancia antes de impuestos", 46.16, 51.60, 2), ("Utilidad neta", 34.22, 38.82, 2), ("Utilidad sin encaje (c)", 21.0, 20.4, 1)],
  derived=("Margen operacional sin encaje", "50,7%", "46,8%"),
  kpi="Sin deuda financiera: caja neta ~$86,7 mil MM. Flujo de caja libre del semestre +26%, que cubre el dividendo. En el semestre la utilidad baja 0,9%. Sin consenso: se compara contra el 2T 2025.",
  tiles=[("P/E de pares", "8,1–10,6x"), ("Valor implícito ($ mil MM)", "~1.225"), ("Rango ($ mil MM)", "1.024–1.340"), ("FCF yield implícito", "~7,0%"), ("ROE 12 meses", "23,7%"), ("Comisión", "1,44%")],
  small="Valor implícito con el P/E (8,1–10,6x) y el EV/EBITDA (8,5–10,9x) de Habitat, Cuprum y Provida · 1,41 millones de afiliados.",
  mirar=["Gastos +12,6% vs. ingresos +4,5%: el margen bajó 4 puntos.", "El encaje explica el 46% de la ganancia antes de impuestos.", "Reforma de pensiones (licitación 2027) con una comisión alta (1,44%).", "Guía 2026 del Grupo Sura, que subió su meta de utilidad."],
  var={"Ingresos por comisiones": 4.5, "Rentabilidad del encaje": 36.4, "Gastos operativos": 12.6, "Ganancia antes de impuestos": 11.8, "Utilidad neta": 13.4, "Utilidad sin encaje (c)": -3.1}),
 dict(id="planvital", t="PLANVITAL", n="AFP PlanVital", s="AFP", px="$280", chg=23,
  pe=8.2, fpe=None, pbv=None, ev=7.3, dy=6.7, roe=None, epsg=15.1, vid="gs9Qtnt98K0", q="PlanVital",
  lede="AFP controlada por la italiana Generali. Ganó licitaciones de nuevos afiliados con una de las comisiones más bajas del sistema (1,16%), lo que le da menor ingreso por cliente y márgenes más bajos que sus pares. Sus ingresos vienen de la comisión; el encaje hace que la utilidad varíe con los mercados.",
  vtitle="AFP PlanVital: utilidad +15% por el encaje, con gastos al alza (2T 2026)",
  cap="Cifras en CLP miles de millones salvo BPA · 2T 2026 vs. 2T 2025",
  rows=[("Ingresos por comisiones", 32.87, 34.81, 2), ("Rentabilidad del encaje", 5.68, 9.71, 2), ("Gastos operativos", 14.77, 17.09, 2),
        ("Ganancia antes de impuestos", 24.42, 28.21, 2), ("Utilidad neta", 18.94, 21.86, 2), ("Utilidad sin encaje (c)", 13.68, 13.51, 2), ("BPA (CLP por acción)", 9.3, 10.7, 1)],
  derived=("Margen operacional sin encaje", "55,0%", "50,9%"),
  kpi="Sin deuda financiera: caja neta ~$54,8 mil MM. En el semestre la utilidad sube 4,7%. Sin consenso: se compara contra el 2T 2025.",
  tiles=[("P/E", "8,2x"), ("EV/EBITDA sin encaje", "7,3x"), ("FCF yield", "9,7%"), ("Dividend Yield", "6,7%"), ("Comisión", "1,16%"), ("Afiliados", "1,59 MM")],
  small="Baja liquidez (~17.500 acciones al día): múltiplos referenciales · P/E 2025: 8,6x · Pares: Habitat 8,1x, Cuprum 10,3x, Provida 10,6x.",
  mirar=["Gastos +15,6% y margen operacional −4 puntos.", "Afiliados estancados mientras AFP Uno crece.", "Reforma de pensiones (licitación 2027, menor encaje).", "Encaje: +71% en el trimestre, pero volátil."],
  var={"Ingresos por comisiones": 5.9, "Rentabilidad del encaje": 70.9, "Gastos operativos": 15.6, "Ganancia antes de impuestos": 15.5, "Utilidad neta": 15.4, "Utilidad sin encaje (c)": -1.3}),
]
